# Generated by Django 3.2 on 2021-08-30 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0002_profile_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcribtion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_resource', models.CharField(max_length=1000)),
                ('is_viewed', models.BooleanField(default=False)),
                ('desc', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.profile')),
            ],
        ),
    ]
