# Generated by Django 3.2 on 2021-08-30 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcribtion',
            name='is_viewed',
        ),
    ]
