# Generated by Django 3.2 on 2021-08-30 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_profile_country'),
        ('subscription', '0002_remove_subcribtion_is_viewed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcribtion',
            new_name='Subscribtion',
        ),
    ]
