# Generated by Django 3.2 on 2021-08-30 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_profile_country'),
        ('subscription', '0003_rename_subcribtion_subscribtion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribtion',
            new_name='Subscription',
        ),
    ]
