# Generated by Django 3.2 on 2021-08-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cityprojectreport',
            old_name='date_modified',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='countryprojectreport',
            old_name='date_modified',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='kebeleprojectreport',
            old_name='date_modified',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='regionprojectreport',
            old_name='date_modified',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='subcityprojectreport',
            old_name='date_modified',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='weredakebeleprojectreport',
            old_name='date_modified',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='weredaprojectreport',
            old_name='date_modified',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='zoneprojectreport',
            old_name='date_modified',
            new_name='date',
        ),
        migrations.AddField(
            model_name='cityprojectreport',
            name='desc',
            field=models.TextField(default='report'),
        ),
        migrations.AddField(
            model_name='cityprojectreport',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='cityprojectreport',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='countryprojectreport',
            name='desc',
            field=models.TextField(default='report'),
        ),
        migrations.AddField(
            model_name='countryprojectreport',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='countryprojectreport',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kebeleprojectreport',
            name='desc',
            field=models.TextField(default='report'),
        ),
        migrations.AddField(
            model_name='kebeleprojectreport',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='kebeleprojectreport',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regionprojectreport',
            name='desc',
            field=models.TextField(default='report'),
        ),
        migrations.AddField(
            model_name='regionprojectreport',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='regionprojectreport',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subcityprojectreport',
            name='desc',
            field=models.TextField(default='report'),
        ),
        migrations.AddField(
            model_name='subcityprojectreport',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='subcityprojectreport',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weredakebeleprojectreport',
            name='desc',
            field=models.TextField(default='report'),
        ),
        migrations.AddField(
            model_name='weredakebeleprojectreport',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='weredakebeleprojectreport',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weredaprojectreport',
            name='desc',
            field=models.TextField(default='report'),
        ),
        migrations.AddField(
            model_name='weredaprojectreport',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='weredaprojectreport',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zoneprojectreport',
            name='desc',
            field=models.TextField(default='report'),
        ),
        migrations.AddField(
            model_name='zoneprojectreport',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='zoneprojectreport',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
