# Generated by Django 3.2 on 2021-04-22 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0002_auto_20210421_1227'),
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionproject',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.zone'),
        ),
    ]
