# Generated by Django 3.2 on 2021-08-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityproject',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='countryproject',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kebeleproject',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regionproject',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcityproject',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weredakebeleproject',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weredaproject',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zoneproject',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
