# Generated by Django 3.2 on 2021-08-08 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CityProjectFiles',
            new_name='CityProjectFile',
        ),
        migrations.RenameModel(
            old_name='CountryProjectFiles',
            new_name='CountryProjectFile',
        ),
        migrations.RenameModel(
            old_name='KebeleProjectFiles',
            new_name='KebeleProjectFile',
        ),
        migrations.RenameModel(
            old_name='RegionProjectFiles',
            new_name='RegionProjectFile',
        ),
        migrations.RenameModel(
            old_name='SubCityProjectFiles',
            new_name='SubCityProjectFile',
        ),
        migrations.RenameModel(
            old_name='WeredaKebeleProjectFiles',
            new_name='WeredaKebeleProjectFile',
        ),
        migrations.RenameModel(
            old_name='WeredaProjectFiles',
            new_name='WeredaProjectFile',
        ),
        migrations.RenameModel(
            old_name='ZoneProjectFiles',
            new_name='ZoneProjectFile',
        ),
    ]
