# Generated by Django 3.2 on 2021-08-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0002_auto_20210803_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryproject',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subcityproject',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
