# Generated by Django 3.2 on 2021-08-01 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_profile_country'),
        ('project_management', '0002_auto_20210801_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityproject',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.profile'),
        ),
        migrations.AddField(
            model_name='cityprojectreport',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.profile'),
        ),
        migrations.AddField(
            model_name='countryproject',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.profile'),
        ),
        migrations.AddField(
            model_name='countryprojectreport',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.profile'),
        ),
        migrations.AddField(
            model_name='kebeleproject',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.profile'),
        ),
        migrations.AddField(
            model_name='kebeleprojectreport',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.profile'),
        ),
        migrations.AddField(
            model_name='regionproject',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.profile'),
        ),
        migrations.AddField(
            model_name='regionprojectreport',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.profile'),
        ),
        migrations.AddField(
            model_name='subcityproject',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.profile'),
        ),
        migrations.AddField(
            model_name='subcityprojectreport',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.profile'),
        ),
        migrations.AddField(
            model_name='weredakebeleproject',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.profile'),
        ),
        migrations.AddField(
            model_name='weredakebeleprojectreport',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.profile'),
        ),
        migrations.AddField(
            model_name='weredaproject',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.profile'),
        ),
        migrations.AddField(
            model_name='weredaprojectreport',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.profile'),
        ),
        migrations.AddField(
            model_name='zoneproject',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.profile'),
        ),
        migrations.AddField(
            model_name='zoneprojectreport',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.profile'),
        ),
    ]
