# Generated by Django 3.2 on 2021-05-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0003_remove_regionproject_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityproject',
            name='img',
            field=models.ImageField(null=True, upload_to='images/cityProject'),
        ),
        migrations.AlterField(
            model_name='kebeleproject',
            name='img',
            field=models.ImageField(null=True, upload_to='images/kebeleProject'),
        ),
        migrations.AlterField(
            model_name='regionproject',
            name='img',
            field=models.ImageField(null=True, upload_to='images/regionProject'),
        ),
        migrations.AlterField(
            model_name='subcityproject',
            name='img',
            field=models.ImageField(null=True, upload_to='images/subCityProject'),
        ),
        migrations.AlterField(
            model_name='weredakebeleproject',
            name='img',
            field=models.ImageField(null=True, upload_to='images/weredaKebeleProject'),
        ),
        migrations.AlterField(
            model_name='weredaproject',
            name='img',
            field=models.ImageField(null=True, upload_to='images/weredaProject'),
        ),
        migrations.AlterField(
            model_name='zoneproject',
            name='img',
            field=models.ImageField(null=True, upload_to='images/zoneProject'),
        ),
    ]
