# Generated by Django 3.2 on 2021-08-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0003_auto_20210803_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionproject',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
