# Generated by Django 3.2 on 2021-07-02 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0005_projectcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='catagory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.projectcategory'),
        ),
    ]
