# Generated by Django 3.2 on 2021-08-13 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0005_auto_20210813_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityProjectReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='files/weredaKebeleProJect')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management.cityprojectreport')),
            ],
        ),
    ]
