# Generated by Django 3.2 on 2021-08-13 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0006_cityprojectreportfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityprojectreportfile',
            name='file',
            field=models.FileField(null=True, upload_to='files/cityProJect/report/'),
        ),
        migrations.CreateModel(
            name='ZoneProjectReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='files/zoneProJect/report/')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management.zoneprojectreport')),
            ],
        ),
        migrations.CreateModel(
            name='WeredaProjectReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='files/weredaProJect/report/')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management.weredaprojectreport')),
            ],
        ),
        migrations.CreateModel(
            name='WeredaKebeleProjectReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='files/weredaKebeleProJect/report/')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management.weredakebeleprojectreport')),
            ],
        ),
        migrations.CreateModel(
            name='SubCityProjectReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='files/subCityProJect/report/')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management.subcityprojectreport')),
            ],
        ),
        migrations.CreateModel(
            name='RegionProjectReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='files/regionProJect/report/')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management.regionprojectreport')),
            ],
        ),
        migrations.CreateModel(
            name='KebeleProjectReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='files/kebeleProJect/report/')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management.kebeleprojectreport')),
            ],
        ),
        migrations.CreateModel(
            name='CountryProjectReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='files/countryProJect/report/')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management.countryprojectreport')),
            ],
        ),
    ]
