# Generated by Django 3.2 on 2021-07-23 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress_management', '0003_auto_20210723_1339'),
        ('project_management', '0007_alter_regionproject_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weredakebeleprojectfiles',
            old_name='wreda_kebele_project',
            new_name='wereda_kebele_project',
        ),
        migrations.AlterField(
            model_name='weredaproject',
            name='img',
            field=models.ImageField(default='images/project-logo.png', null=True, upload_to='images/weredaProject'),
        ),
        migrations.AlterField(
            model_name='zoneproject',
            name='img',
            field=models.ImageField(null=True, upload_to='images/weredaProject'),
        ),
        migrations.CreateModel(
            name='ZoneProjectProgress',
            fields=[
                ('progress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='progress_management.progress')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('zone_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.zoneproject')),
            ],
            bases=('progress_management.progress',),
        ),
        migrations.CreateModel(
            name='WeredaProjectProgress',
            fields=[
                ('progress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='progress_management.progress')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('wereda_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.weredaproject')),
            ],
            bases=('progress_management.progress',),
        ),
        migrations.CreateModel(
            name='WeredaKebeleProjectProgress',
            fields=[
                ('progress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='progress_management.progress')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('wereda_kebele_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.weredakebeleproject')),
            ],
            bases=('progress_management.progress',),
        ),
        migrations.CreateModel(
            name='SubCityProjectProgress',
            fields=[
                ('progress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='progress_management.progress')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('sub_city_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.subcityproject')),
            ],
            bases=('progress_management.progress',),
        ),
        migrations.CreateModel(
            name='RegionProjectProgress',
            fields=[
                ('progress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='progress_management.progress')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('region_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.regionproject')),
            ],
            bases=('progress_management.progress',),
        ),
        migrations.CreateModel(
            name='KebeleProjectProgress',
            fields=[
                ('progress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='progress_management.progress')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('kebele_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.kebeleproject')),
            ],
            bases=('progress_management.progress',),
        ),
        migrations.CreateModel(
            name='CountryProjectProgress',
            fields=[
                ('progress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='progress_management.progress')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('country_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.countryproject')),
            ],
            bases=('progress_management.progress',),
        ),
        migrations.CreateModel(
            name='CityProjectProgress',
            fields=[
                ('progress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='progress_management.progress')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('city_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.cityproject')),
            ],
            bases=('progress_management.progress',),
        ),
    ]
