# Generated by Django 3.2 on 2021-08-19 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0007_auto_20210813_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryprojectreport',
            name='is_assesed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cityprojectreport',
            name='worklevel',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='countryprojectreport',
            name='worklevel',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='kebeleprojectreport',
            name='worklevel',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='regionprojectreport',
            name='worklevel',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='subcityprojectreport',
            name='worklevel',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='weredakebeleprojectreport',
            name='worklevel',
            field=models.IntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='weredaprojectreport',
            name='worklevel',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='zoneprojectreport',
            name='worklevel',
            field=models.IntegerField(default=3),
        ),
        migrations.CreateModel(
            name='CountryProjectReportAssesment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worklevel', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=1000, null=True)),
                ('desc', models.TextField(default='report')),
                ('percentage', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management.countryprojectreport')),
            ],
        ),
    ]
