# Generated by Django 3.2 on 2021-08-20 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0008_auto_20210819_1507'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CountryProjectReportAssesment',
            new_name='CountryProjectReportAssessment',
        ),
    ]
