# Generated by Django 3.2 on 2021-07-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0009_alter_countryproject_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityproject',
            name='img',
            field=models.ImageField(default='images/project-logo.png', null=True, upload_to='images/cityProject'),
        ),
        migrations.AlterField(
            model_name='kebeleproject',
            name='img',
            field=models.ImageField(default='images/project-logo.png', null=True, upload_to='images/kebeleProject'),
        ),
        migrations.AlterField(
            model_name='subcityproject',
            name='img',
            field=models.ImageField(default='images/project-logo.png', null=True, upload_to='images/subCityProject'),
        ),
        migrations.AlterField(
            model_name='weredakebeleproject',
            name='img',
            field=models.ImageField(default='images/project-logo.png', null=True, upload_to='images/weredaKebeleProject'),
        ),
        migrations.AlterField(
            model_name='zoneproject',
            name='img',
            field=models.ImageField(default='images/project-logo.png', null=True, upload_to='images/weredaProject'),
        ),
    ]
