# Generated by Django 3.2 on 2021-08-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0009_rename_countryprojectreportassesment_countryprojectreportassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryProjectStackeHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('img1', models.ImageField(null=True, upload_to='images/project/stackeholder/')),
                ('desc', models.TextField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('project', models.ManyToManyField(null=True, to='project_management.CountryProject')),
            ],
        ),
    ]
