# Generated by Django 3.2 on 2021-08-25 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0010_countryprojectstackeholder'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryProjectRelatedIsue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('img1', models.ImageField(null=True, upload_to='images/country-project/related-isue/')),
                ('desc', models.TextField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('project', models.ManyToManyField(null=True, to='project_management.CountryProject')),
            ],
        ),
        migrations.AlterField(
            model_name='countryprojectstackeholder',
            name='img1',
            field=models.ImageField(null=True, upload_to='images/country-project/stackeholder/'),
        ),
        migrations.CreateModel(
            name='CountryProjectRelatedIsueFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='files/countryProJect/related-isue/')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('country_project_related_isue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management.countryprojectrelatedisue')),
            ],
        ),
    ]
