# Generated by Django 3.2 on 2021-07-28 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0002_auto_20210421_1227'),
        ('project_management', '0010_auto_20210728_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryproject',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='location_management.country'),
        ),
    ]
