# Generated by Django 3.2 on 2021-07-31 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_management', '0001_initial'),
        ('project_management', '0011_alter_countryproject_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cityprojectprogress',
            old_name='city_project',
            new_name='project',
        ),
        migrations.RemoveField(
            model_name='countryprojectprogress',
            name='country_project',
        ),
        migrations.RemoveField(
            model_name='kebeleprojectprogress',
            name='kebele_project',
        ),
        migrations.RemoveField(
            model_name='regionprojectprogress',
            name='region_project',
        ),
        migrations.RemoveField(
            model_name='subcityprojectprogress',
            name='sub_city_project',
        ),
        migrations.RemoveField(
            model_name='weredakebeleprojectprogress',
            name='wereda_kebele_project',
        ),
        migrations.RemoveField(
            model_name='weredaprojectprogress',
            name='wereda_project',
        ),
        migrations.RemoveField(
            model_name='zoneprojectprogress',
            name='zone_project',
        ),
        migrations.AddField(
            model_name='countryprojectprogress',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_management.countryproject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kebeleprojectprogress',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_management.kebeleproject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regionprojectprogress',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_management.regionproject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcityprojectprogress',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_management.subcityproject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weredakebeleprojectprogress',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_management.weredakebeleproject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weredaprojectprogress',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_management.weredaproject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zoneprojectprogress',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_management.zoneproject'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ZoneProjectReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='report_management.report')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.zoneproject')),
            ],
            bases=('report_management.report',),
        ),
        migrations.CreateModel(
            name='WeredaProjectReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='report_management.report')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.weredaproject')),
            ],
            bases=('report_management.report',),
        ),
        migrations.CreateModel(
            name='WeredaKebeleProjectReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='report_management.report')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.weredakebeleproject')),
            ],
            bases=('report_management.report',),
        ),
        migrations.CreateModel(
            name='SubCityProjectReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='report_management.report')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.subcityproject')),
            ],
            bases=('report_management.report',),
        ),
        migrations.CreateModel(
            name='RegionProjectReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='report_management.report')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.regionproject')),
            ],
            bases=('report_management.report',),
        ),
        migrations.CreateModel(
            name='KebeleProjectReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='report_management.report')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.kebeleproject')),
            ],
            bases=('report_management.report',),
        ),
        migrations.CreateModel(
            name='CountryProjectReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='report_management.report')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.countryproject')),
            ],
            bases=('report_management.report',),
        ),
        migrations.CreateModel(
            name='CityProjectReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='report_management.report')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.cityproject')),
            ],
            bases=('report_management.report',),
        ),
    ]
