# Generated by Django 3.2 on 2021-08-25 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0011_auto_20210825_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryprojectrelatedisue',
            name='project',
        ),
        migrations.AddField(
            model_name='countryprojectrelatedisue',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.countryproject'),
        ),
    ]
