# Generated by Django 3.2 on 2021-08-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0012_auto_20210825_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryprojectstackeholder',
            name='project',
            field=models.ManyToManyField(to='project_management.CountryProject'),
        ),
    ]
