# Generated by Django 3.2 on 2021-09-01 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0014_auto_20210830_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryprojectreport',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.countryproject'),
        ),
        migrations.AlterField(
            model_name='countryprojectreportreview',
            name='desc',
            field=models.TextField(default='report review'),
        ),
    ]
