# Generated by Django 3.2 on 2021-07-02 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_management', '0005_projectcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('desc', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZoneProjectComplain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('desc', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.zoneproject')),
            ],
        ),
        migrations.CreateModel(
            name='WeredaProjectComplain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('desc', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.weredaproject')),
            ],
        ),
        migrations.CreateModel(
            name='WeredaKebeleProjectComplain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('desc', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.weredakebeleproject')),
            ],
        ),
        migrations.CreateModel(
            name='SubCityProjectComplain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('desc', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.subcityproject')),
            ],
        ),
        migrations.CreateModel(
            name='RegionProjectComplain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('desc', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.regionproject')),
            ],
        ),
        migrations.CreateModel(
            name='KebeleProjectComplain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('desc', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.kebeleproject')),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('desc', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('type', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='complain_management.complaincategory')),
            ],
        ),
        migrations.CreateModel(
            name='CityProjectComplain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('desc', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.cityproject')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectComplain',
            fields=[
                ('complain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='complain_management.complain')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.project')),
            ],
            bases=('complain_management.complain',),
        ),
    ]
