# Generated by Django 3.2 on 2021-07-03 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0006_alter_project_catagory'),
        ('complain_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectComplain',
            new_name='CountryProjectComplain',
        ),
        migrations.RemoveField(
            model_name='cityprojectcomplain',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cityprojectcomplain',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='cityprojectcomplain',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cityprojectcomplain',
            name='title',
        ),
        migrations.RemoveField(
            model_name='complain',
            name='type',
        ),
        migrations.RemoveField(
            model_name='kebeleprojectcomplain',
            name='date',
        ),
        migrations.RemoveField(
            model_name='kebeleprojectcomplain',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='kebeleprojectcomplain',
            name='id',
        ),
        migrations.RemoveField(
            model_name='kebeleprojectcomplain',
            name='title',
        ),
        migrations.RemoveField(
            model_name='regionprojectcomplain',
            name='date',
        ),
        migrations.RemoveField(
            model_name='regionprojectcomplain',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='regionprojectcomplain',
            name='id',
        ),
        migrations.RemoveField(
            model_name='regionprojectcomplain',
            name='title',
        ),
        migrations.RemoveField(
            model_name='subcityprojectcomplain',
            name='date',
        ),
        migrations.RemoveField(
            model_name='subcityprojectcomplain',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='subcityprojectcomplain',
            name='id',
        ),
        migrations.RemoveField(
            model_name='subcityprojectcomplain',
            name='title',
        ),
        migrations.RemoveField(
            model_name='weredakebeleprojectcomplain',
            name='date',
        ),
        migrations.RemoveField(
            model_name='weredakebeleprojectcomplain',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='weredakebeleprojectcomplain',
            name='id',
        ),
        migrations.RemoveField(
            model_name='weredakebeleprojectcomplain',
            name='title',
        ),
        migrations.RemoveField(
            model_name='weredaprojectcomplain',
            name='date',
        ),
        migrations.RemoveField(
            model_name='weredaprojectcomplain',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='weredaprojectcomplain',
            name='id',
        ),
        migrations.RemoveField(
            model_name='weredaprojectcomplain',
            name='title',
        ),
        migrations.RemoveField(
            model_name='zoneprojectcomplain',
            name='date',
        ),
        migrations.RemoveField(
            model_name='zoneprojectcomplain',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='zoneprojectcomplain',
            name='id',
        ),
        migrations.RemoveField(
            model_name='zoneprojectcomplain',
            name='title',
        ),
        migrations.AddField(
            model_name='cityprojectcomplain',
            name='complain_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='complain_management.complain'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kebeleprojectcomplain',
            name='complain_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='complain_management.complain'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regionprojectcomplain',
            name='complain_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='complain_management.complain'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcityprojectcomplain',
            name='complain_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='complain_management.complain'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weredakebeleprojectcomplain',
            name='complain_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='complain_management.complain'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weredaprojectcomplain',
            name='complain_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='complain_management.complain'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zoneprojectcomplain',
            name='complain_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='complain_management.complain'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='countryprojectcomplain',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.countryproject'),
        ),
    ]
