# Generated by Django 3.2 on 2021-07-23 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0001_initial'),
        ('complain_management', '0003_complain_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneProjectComplainFile',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='file_management.file')),
                ('complain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='complain_management.zoneprojectcomplain')),
            ],
            bases=('file_management.file',),
        ),
        migrations.CreateModel(
            name='WeredaProjectComplainFile',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='file_management.file')),
                ('complain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='complain_management.weredaprojectcomplain')),
            ],
            bases=('file_management.file',),
        ),
        migrations.CreateModel(
            name='WeredaKebeleProjectComplainFile',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='file_management.file')),
                ('complain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='complain_management.weredakebeleprojectcomplain')),
            ],
            bases=('file_management.file',),
        ),
        migrations.CreateModel(
            name='SubCityProjectComplainFile',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='file_management.file')),
                ('complain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='complain_management.subcityprojectcomplain')),
            ],
            bases=('file_management.file',),
        ),
        migrations.CreateModel(
            name='RegionProjectComplainFile',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='file_management.file')),
                ('complain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='complain_management.regionprojectcomplain')),
            ],
            bases=('file_management.file',),
        ),
        migrations.CreateModel(
            name='KebeleProjectComplainFile',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='file_management.file')),
                ('complain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='complain_management.kebeleprojectcomplain')),
            ],
            bases=('file_management.file',),
        ),
        migrations.CreateModel(
            name='CountryProjectComplainFile',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='file_management.file')),
                ('complain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='complain_management.countryprojectcomplain')),
            ],
            bases=('file_management.file',),
        ),
        migrations.CreateModel(
            name='CityProjectComplainFile',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='file_management.file')),
                ('complain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='complain_management.cityprojectcomplain')),
            ],
            bases=('file_management.file',),
        ),
    ]
