# Generated by Django 3.2 on 2021-09-02 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_rename_notification_countrynotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryNotification',
        ),
    ]
