# Generated by Django 3.2 on 2021-08-01 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('location', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('worklevel', models.IntegerField(null=True)),
                ('role', models.IntegerField(null=True)),
                ('experiance', models.TextField(null=True)),
                ('img', models.ImageField(default='profile/images/avatar.jpg', null=True, upload_to='profile/images')),
                ('date', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.city')),
                ('kebele', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.kebele')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.region')),
                ('sub_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.subcity')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('wereda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.wereda')),
                ('wereda_kebele', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.weredakebele')),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='images1')),
                ('date', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.profile')),
            ],
        ),
        migrations.CreateModel(
            name='InfoPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=2000)),
                ('date', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.city')),
                ('kebele', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.kebele')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.region')),
                ('sub_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.subcity')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wereda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.wereda')),
                ('wereda_kebele', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.weredakebele')),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.zone')),
            ],
        ),
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.contact')),
            ],
        ),
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=500)),
                ('date', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=2000)),
                ('date', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.city')),
                ('kebele', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.kebele')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.region')),
                ('sub_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.subcity')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wereda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.wereda')),
                ('wereda_kebele', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.weredakebele')),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=2000)),
                ('date', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.city')),
                ('kebele', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.kebele')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.region')),
                ('sub_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.subcity')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wereda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.wereda')),
                ('wereda_kebele', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.weredakebele')),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.zone')),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=500)),
                ('education', models.TextField(null=True)),
                ('desc', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('contact', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.contact')),
            ],
        ),
    ]
