# Generated by Django 3.2 on 2021-04-22 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location_management', '0002_auto_20210421_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('date', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.city')),
                ('kebele', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.kebele')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.region')),
                ('sub_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.subcity')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wereda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.wereda')),
                ('wereda_kebele', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.weredakebele')),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.zone')),
            ],
        ),
        migrations.CreateModel(
            name='InfoPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=2000)),
                ('date', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.city')),
                ('kebele', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.kebele')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.region')),
                ('sub_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.subcity')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wereda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.wereda')),
                ('wereda_kebele', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.weredakebele')),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=2000)),
                ('date', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.city')),
                ('kebele', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.kebele')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.region')),
                ('sub_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.subcity')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wereda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.wereda')),
                ('wereda_kebele', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.weredakebele')),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=2000)),
                ('date', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.city')),
                ('kebele', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.kebele')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.region')),
                ('sub_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.subcity')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wereda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.wereda')),
                ('wereda_kebele', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.weredakebele')),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.zone')),
            ],
        ),
    ]
