# Generated by Django 3.2 on 2021-04-23 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0002_auto_20210421_1227'),
        ('user_management', '0003_auto_20210422_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.city'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='profile/images/empty-avatar.png', null=True, upload_to='profile/images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='kebele',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.kebele'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.region'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sub_city',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.subcity'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wereda',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.wereda'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wereda_kebele',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.weredakebele'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='worklevel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.worklevel'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zone',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.zone'),
        ),
    ]
