# Generated by Django 3.2 on 2021-07-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='profile/images/avatar.jpg', null=True, upload_to='profile/images'),
        ),
    ]
