# Generated by Django 3.2 on 2021-07-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level_management', '0001_initial'),
        ('user_management', '0008_auto_20210723_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.ManyToManyField(null=True, to='user_management.Role'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='worklevel',
        ),
        migrations.AddField(
            model_name='profile',
            name='worklevel',
            field=models.ManyToManyField(null=True, to='level_management.Level'),
        ),
    ]
