# Generated by Django 3.2 on 2021-07-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_auto_20210727_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='worklevel',
        ),
    ]
