# Generated by Django 3.2 on 2021-05-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_management', '0003_auto_20210518_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityprojectcomment',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='countryprojectcomment',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='kebeleprojectcomment',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='regionprojectcomment',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subcityprojectcomment',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='weredakebeleprojectcomment',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='weredaprojectcomment',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='zoneprojectcomment',
            name='level',
            field=models.IntegerField(null=True),
        ),
    ]
