# Generated by Django 3.2 on 2021-05-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_management', '0004_auto_20210519_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityprojectcomment',
            name='level',
            field=models.IntegerField(default=5, null=True),
        ),
        migrations.AlterField(
            model_name='countryprojectcomment',
            name='level',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='kebeleprojectcomment',
            name='level',
            field=models.IntegerField(default=7, null=True),
        ),
        migrations.AlterField(
            model_name='regionprojectcomment',
            name='level',
            field=models.IntegerField(default=2, null=True),
        ),
        migrations.AlterField(
            model_name='subcityprojectcomment',
            name='level',
            field=models.IntegerField(default=6, null=True),
        ),
        migrations.AlterField(
            model_name='weredakebeleprojectcomment',
            name='level',
            field=models.IntegerField(default=8, null=True),
        ),
        migrations.AlterField(
            model_name='weredaprojectcomment',
            name='level',
            field=models.IntegerField(default=4, null=True),
        ),
        migrations.AlterField(
            model_name='zoneprojectcomment',
            name='level',
            field=models.IntegerField(default=3, null=True),
        ),
    ]
