# Generated by Django 3.2 on 2021-05-21 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_alter_profile_user'),
        ('comment_management', '0005_auto_20210519_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityprojectcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='countryprojectcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projectcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='regionprojectcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subcityprojectcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='weredakebeleprojectcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='weredaprojectcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='zoneprojectcomment',
            name='user',
        ),
        migrations.AddField(
            model_name='cityprojectcomment',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.profile'),
        ),
        migrations.AddField(
            model_name='countryprojectcomment',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.profile'),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.profile'),
        ),
        migrations.AddField(
            model_name='regionprojectcomment',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.profile'),
        ),
        migrations.AddField(
            model_name='subcityprojectcomment',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.profile'),
        ),
        migrations.AddField(
            model_name='weredakebeleprojectcomment',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.profile'),
        ),
        migrations.AddField(
            model_name='weredaprojectcomment',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.profile'),
        ),
        migrations.AddField(
            model_name='zoneprojectcomment',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.profile'),
        ),
        migrations.AlterField(
            model_name='kebeleprojectcomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.profile'),
        ),
    ]
