# Generated by Django 3.2 on 2021-07-27 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level_management', '0002_level_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='profile',
        ),
    ]
