# Generated by Django 3.2 on 2021-07-12 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('url', models.TextField()),
                ('views', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('progress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='progress_management.progress')),
            ],
        ),
    ]
