# Generated by Django 3.2 on 2021-07-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
