# Generated by Django 3.2 on 2021-04-21 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcity',
            old_name='wereda',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='weredakebele',
            old_name='city',
            new_name='sub_city',
        ),
    ]
