# Generated by Django 3.2 on 2021-08-30 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification_management', '0003_notification_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='profile',
        ),
    ]
