# Generated by Django 3.2 on 2021-07-27 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_auto_20210727_1343'),
        ('role_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.profile'),
        ),
    ]
