# Generated by Django 3.2 on 2021-07-27 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role_management', '0002_role_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='profile',
        ),
    ]
